### ISSUE TITLE
Face Re-enactment

### ISSUE THREAD

**Issue by amil-rp-work** [AnetaTexler/FaceBlit#10]
Hey @AnetaTexler 
Thanks for sharing such awesome work. I can think of so many fun applications for this :)

I was wondering if I can use the work to do the re-enactment of human videos? What if i select the same source image as style and this will help me achieve neural head re-enactment work?

**Comment by AnetaTexler** [comment]
Hello @amil-rp-work

Thanks for your interest! (and sorry for the late reply)

That is an interesting question. This project was designed, and all of experiments we did were with artistic images - paintings.
However, you can definitely try your suggestion, you will get some results, but I can't promise they will be visually pleasing ones.

It is easy to try, actually. As a style, instead of a painting, pick a real photo of a person. Follow the readme, there is explained how to create custom styles, and run the C++ version on a video (e.g., video of you) or Android version on a mobile phone. 

I am really curious, let me know if you try it, and feel free to post some results here in this issue thread!
